name: PushImage

on: push

permissions:
  contents: read
  packages: write

env:
  OKAPI_URL: http://okapi:9130
  SLEEP: 0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rspec
    - name: Verify output file
      run: cat spec/fixtures/report_file.csv

  build-and-push-image:
    runs-on: ubuntu-latest
    steps:

    - name: Extract branch name
      id: extract_branch
      run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/sul-dlss/cybersource-rest-ruby:${{ steps.extract_branch.outputs.branch }}
        file: Dockerfile
